# - name: "install nodejs source shell"
#   become: true
#   shell: |
#     curl -fsSL "https://deb.nodesource.com/setup_13.x" | sudo -E bash -

- name: "install node.js"
  become: true
  apt:
    name: ['nodejs', 'npm']
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    state: latest
    production: yes

# - name: "Move ENV Files"
#   become: true
#   copy:
#     src: myenv.sh
#     dst: /etc/profile.d/